// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOzsqFxOVljbWmbyigz_45iGxa8AJCQ20',
    appId: '1:134875107158:android:cc2b37b2d5f28eb1bc50f7',
    messagingSenderId: '134875107158',
    projectId: 'hybridapp-8e623',
    storageBucket: 'hybridapp-8e623.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADtek7Xm8W8qRwqVaGzR80E25HbBV159Y',
    appId: '1:134875107158:ios:3577a7e94d4d33a8bc50f7',
    messagingSenderId: '134875107158',
    projectId: 'hybridapp-8e623',
    storageBucket: 'hybridapp-8e623.appspot.com',
    iosBundleId: 'com.example.passwordManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADtek7Xm8W8qRwqVaGzR80E25HbBV159Y',
    appId: '1:134875107158:ios:3105a93a29b7736ebc50f7',
    messagingSenderId: '134875107158',
    projectId: 'hybridapp-8e623',
    storageBucket: 'hybridapp-8e623.appspot.com',
    iosBundleId: 'com.example.passwordManager.RunnerTests',
  );
}
